apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "openchain.fullname" . }}
  labels:
    app: {{ template "openchain.name" . }}
    chart: {{ template "openchain.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "openchain.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "openchain.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: config
          secret:
            secretName: {{ .Values.deployment.config_secret }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: openchain
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /openchain/Openchain/data
              name: config
          livenessProbe:
            exec:
              command:
              - ls
              - /openchain/
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /info
              port: openchain
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
